use crate::AuthError;
use serde::{Deserialize, Serialize};

/// Configuration bundle for an OAuth 2.0 / OpenID Connect provider.
///
/// An instance fully describes the endpoints and credentials needed to perform
/// the Authorization Code flow against a single provider (e.g. Google, GitHub,
/// a self-hosted Keycloak).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OAuthConfig {
    /// The OAuth 2.0 `client_id` registered with the provider.
    pub client_id: String,
    /// The OAuth 2.0 `client_secret` issued by the provider.
    pub client_secret: String,
    /// The provider's authorization endpoint URL (where the user is redirected).
    pub auth_url: String,
    /// The provider's token endpoint URL (where the auth code is exchanged).
    pub token_url: String,
    /// Optional UserInfo endpoint URL. Required only if you intend to call
    /// [`Oauth2Client::get_user_info`].
    pub userinfo_url: Option<String>,
    /// The callback URI registered with the provider — the user is redirected
    /// here after authorization.
    pub redirect_uri: String,
}

/// The response returned by an OAuth 2.0 token endpoint after a successful
/// authorization code exchange.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenResponse {
    /// The bearer access token used to authorise subsequent API requests.
    pub access_token: String,
    /// Token type — almost always `"Bearer"`.
    pub token_type: String,
    /// Lifetime of the access token in seconds (if provided by the server).
    pub expires_in: Option<u64>,
    /// The OIDC ID Token (a signed JWT) — present when the `openid` scope was
    /// requested.
    pub id_token: Option<String>,
    /// A refresh token that can be used to obtain new access tokens without
    /// user interaction.
    pub refresh_token: Option<String>,
}

/// User profile data returned by the OIDC UserInfo endpoint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInfo {
    /// The subject identifier — a unique, stable user ID from the provider.
    pub sub: String,
    /// The user's display name (may be absent depending on granted scopes).
    pub name: Option<String>,
    /// The user's email address (may be absent depending on granted scopes).
    pub email: Option<String>,
    /// Application-defined roles, if the provider includes them in its
    /// UserInfo response (non-standard claim).
    pub roles: Option<Vec<String>>,
}

/// A minimal HTTP client abstraction used by [`Oauth2Client`].
///
/// By programming against this trait rather than a concrete HTTP library, the
/// OAuth logic remains portable across WASI, native, and test environments.
/// In tests, implementors can return canned responses to verify request
/// construction without performing real network I/O.
pub trait HttpClient {
    /// Sends an HTTP **POST** request and returns the response body as a string.
    ///
    /// * `url` — the request URL.
    /// * `headers` — a slice of `(name, value)` header pairs.
    /// * `body` — the request body (typically `application/x-www-form-urlencoded`).
    fn post(&self, url: &str, headers: &[(&str, &str)], body: &str) -> Result<String, AuthError>;

    /// Sends an HTTP **GET** request and returns the response body as a string.
    ///
    /// * `url` — the request URL.
    /// * `headers` — a slice of `(name, value)` header pairs.
    fn get(&self, url: &str, headers: &[(&str, &str)]) -> Result<String, AuthError>;
}

/// A stateless OAuth 2.0 / OpenID Connect client.
///
/// All methods are **static** — `Oauth2Client` carries no state and is never
/// instantiated. Configuration is passed in via [`OAuthConfig`] and HTTP I/O
/// is delegated to any [`HttpClient`] implementor.
/// A PKCE (Proof Key for Code Exchange) challenge.
///
/// Used to secure the OAuth 2.0 Authorization Code flow against interception attacks.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PkceChallenge {
    /// The secret verifier generated by the client.
    pub code_verifier: String,
    /// The challenge string sent to the authorization server.
    pub code_challenge: String,
}

impl PkceChallenge {
    /// Generates a random 64-character `code_verifier` (entropy > 256 bits)
    /// and its SHA-256 S256 method `code_challenge`.
    pub fn generate() -> Self {
        let mut rng = rand::thread_rng();
        const CHARSET: &[u8] =
            b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";
        let code_verifier: String = (0..64)
            .map(|_| {
                use rand::Rng;
                let idx = rng.gen_range(0..CHARSET.len());
                CHARSET[idx] as char
            })
            .collect();

        use sha2::{Digest, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(code_verifier.as_bytes());
        let hash_result = hasher.finalize();

        use base64::Engine;
        use base64::engine::general_purpose::URL_SAFE_NO_PAD;
        let code_challenge = URL_SAFE_NO_PAD.encode(hash_result);

        Self {
            code_verifier,
            code_challenge,
        }
    }
}

pub struct Oauth2Client;

impl Oauth2Client {
    /// Builds the full authorization URL to which the user-agent should be
    /// redirected to begin the OAuth 2.0 Authorization Code flow.
    ///
    /// The resulting URL includes the `response_type=code`, `client_id`,
    /// `redirect_uri`, `state`, and `scope` query parameters, all
    /// percent-encoded.
    ///
    /// # Arguments
    ///
    /// * `config` — provider configuration (only `auth_url`, `client_id`, and
    ///   `redirect_uri` are used).
    /// * `state` — an opaque CSRF token that the provider will echo back.
    /// * `scope` — space-separated list of OAuth scopes (e.g. `"openid email"`).
    /// * `pkce` — optional PKCE challenge configuration.
    pub fn generate_auth_url(
        config: &OAuthConfig,
        state: &str,
        scope: &str,
        pkce: Option<&PkceChallenge>,
    ) -> String {
        let auth_url = if config.auth_url.contains('?') {
            format!("{}&", config.auth_url)
        } else {
            format!("{}?", config.auth_url)
        };

        let mut url = format!(
            "{}response_type=code&client_id={}&redirect_uri={}&state={}&scope={}",
            auth_url,
            urlencoding::encode(&config.client_id),
            urlencoding::encode(&config.redirect_uri),
            urlencoding::encode(state),
            urlencoding::encode(scope)
        );

        if let Some(challenge) = pkce {
            url.push_str(&format!(
                "&code_challenge={}&code_challenge_method=S256",
                urlencoding::encode(&challenge.code_challenge)
            ));
        }

        url
    }

    /// Exchanges an authorization code for an access token (and optionally an
    /// ID token and refresh token) by POSTing to the provider's token endpoint.
    ///
    /// The request body is `application/x-www-form-urlencoded` with
    /// `grant_type=authorization_code` and the code, redirect URI, client ID,
    /// and client secret.
    ///
    /// # Errors
    ///
    /// Returns [`AuthError`] if the HTTP request fails or the response cannot
    /// be deserialized into a [`TokenResponse`].
    pub fn exchange_code(
        config: &OAuthConfig,
        code: &str,
        client: &impl HttpClient,
        code_verifier: Option<&str>,
    ) -> Result<TokenResponse, AuthError> {
        let mut body = format!(
            "grant_type=authorization_code&code={}&redirect_uri={}&client_id={}&client_secret={}",
            urlencoding::encode(code),
            urlencoding::encode(&config.redirect_uri),
            urlencoding::encode(&config.client_id),
            urlencoding::encode(&config.client_secret)
        );

        if let Some(verifier) = code_verifier {
            body.push_str(&format!("&code_verifier={}", urlencoding::encode(verifier)));
        }

        let headers = [
            ("Content-Type", "application/x-www-form-urlencoded"),
            ("Accept", "application/json"),
        ];

        let resp_body = client.post(&config.token_url, &headers, &body)?;
        let token_resp: TokenResponse = serde_json::from_str(&resp_body).map_err(|_| {
            AuthError::Crypto("Failed to parse token response from provider".to_string())
        })?;
        Ok(token_resp)
    }

    /// Extends raw error cleanup on UserInfo responses.
    pub fn get_user_info(
        config: &OAuthConfig,
        access_token: &str,
        client: &impl HttpClient,
    ) -> Result<UserInfo, AuthError> {
        let userinfo_url = config
            .userinfo_url
            .as_ref()
            .ok_or_else(|| AuthError::Crypto("Userinfo endpoint not configured".to_string()))?;

        let auth_header = format!("Bearer {}", access_token);
        let headers = [
            ("Authorization", auth_header.as_str()),
            ("Accept", "application/json"),
        ];

        let resp_body = client.get(userinfo_url, &headers)?;
        let user_info: UserInfo = serde_json::from_str(&resp_body).map_err(|_| {
            AuthError::Crypto("Failed to parse userinfo response from provider".to_string())
        })?;
        Ok(user_info)
    }

    /// Parses a raw OIDC discovery metadata JSON string and constructs an
    /// [`OAuthConfig`].
    ///
    /// The JSON must contain at least `authorization_endpoint` and
    /// `token_endpoint`; `userinfo_endpoint` is optional. The caller supplies
    /// the client credentials and redirect URI.
    ///
    /// # Errors
    ///
    /// Returns [`AuthError::Crypto`] if `metadata_json` cannot be deserialized.
    pub fn parse_oidc_discovery(
        client_id: &str,
        client_secret: &str,
        redirect_uri: &str,
        metadata_json: &str,
    ) -> Result<OAuthConfig, AuthError> {
        #[derive(Deserialize)]
        struct DiscoveryMetadata {
            authorization_endpoint: String,
            token_endpoint: String,
            userinfo_endpoint: Option<String>,
        }

        let meta: DiscoveryMetadata = serde_json::from_str(metadata_json)
            .map_err(|e| AuthError::Crypto(format!("Failed to parse OIDC metadata: {}", e)))?;

        Ok(OAuthConfig {
            client_id: client_id.to_string(),
            client_secret: client_secret.to_string(),
            auth_url: meta.authorization_endpoint,
            token_url: meta.token_endpoint,
            userinfo_url: meta.userinfo_endpoint,
            redirect_uri: redirect_uri.to_string(),
        })
    }

    /// Fetches the OIDC discovery document from `discovery_url` and parses it
    /// into an [`OAuthConfig`].
    ///
    /// This is a convenience wrapper that combines an HTTP GET with
    /// [`parse_oidc_discovery`](Self::parse_oidc_discovery).
    ///
    /// A typical `discovery_url` looks like
    /// `https://provider.example/.well-known/openid-configuration`.
    ///
    /// # Errors
    ///
    /// Returns [`AuthError`] if the HTTP request or JSON parsing fails.
    pub fn fetch_oidc_config(
        client_id: &str,
        client_secret: &str,
        redirect_uri: &str,
        discovery_url: &str,
        client: &impl HttpClient,
    ) -> Result<OAuthConfig, AuthError> {
        let headers = [("Accept", "application/json")];
        let meta_json = client.get(discovery_url, &headers)?;
        Self::parse_oidc_discovery(client_id, client_secret, redirect_uri, &meta_json)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    struct MockHttpClient {
        response_body: String,
        last_request: Mutex<Option<(String, String, String)>>, // (method, url, body)
    }

    impl HttpClient for MockHttpClient {
        fn post(
            &self,
            url: &str,
            _headers: &[(&str, &str)],
            body: &str,
        ) -> Result<String, AuthError> {
            let mut req = self.last_request.lock().unwrap();
            *req = Some(("POST".to_string(), url.to_string(), body.to_string()));
            Ok(self.response_body.clone())
        }

        fn get(&self, url: &str, _headers: &[(&str, &str)]) -> Result<String, AuthError> {
            let mut req = self.last_request.lock().unwrap();
            *req = Some(("GET".to_string(), url.to_string(), String::new()));
            Ok(self.response_body.clone())
        }
    }

    #[test]
    fn test_generate_auth_url() {
        let config = OAuthConfig {
            client_id: "id123".to_string(),
            client_secret: "sec123".to_string(),
            auth_url: "https://auth.com".to_string(),
            token_url: "https://token.com".to_string(),
            userinfo_url: None,
            redirect_uri: "https://app.com/callback".to_string(),
        };

        let url = Oauth2Client::generate_auth_url(&config, "mystate", "openid email", None);
        assert!(url.contains("client_id=id123"));
        assert!(url.contains("state=mystate"));
        assert!(url.contains("scope=openid%20email"));
    }

    #[test]
    fn test_pkce_auth_flow() {
        let config = OAuthConfig {
            client_id: "id123".to_string(),
            client_secret: "sec123".to_string(),
            auth_url: "https://auth.com".to_string(),
            token_url: "https://token.com".to_string(),
            userinfo_url: None,
            redirect_uri: "https://app.com/callback".to_string(),
        };

        let challenge = PkceChallenge::generate();
        assert_eq!(challenge.code_verifier.len(), 64);
        assert!(!challenge.code_challenge.is_empty());

        let url =
            Oauth2Client::generate_auth_url(&config, "mystate", "openid email", Some(&challenge));
        assert!(url.contains(&format!(
            "code_challenge={}",
            urlencoding::encode(&challenge.code_challenge)
        )));
        assert!(url.contains("code_challenge_method=S256"));

        let mock_resp =
            r#"{"access_token":"t123","token_type":"Bearer","expires_in":3600,"id_token":"id123"}"#;
        let mock_client = MockHttpClient {
            response_body: mock_resp.to_string(),
            last_request: Mutex::new(None),
        };

        let token_resp = Oauth2Client::exchange_code(
            &config,
            "mycode",
            &mock_client,
            Some(&challenge.code_verifier),
        )
        .unwrap();
        assert_eq!(token_resp.access_token, "t123");

        let req = mock_client.last_request.lock().unwrap().clone().unwrap();
        assert!(
            req.2
                .contains(&format!("code_verifier={}", challenge.code_verifier))
        );
    }

    #[test]
    fn test_exchange_code() {
        let config = OAuthConfig {
            client_id: "id123".to_string(),
            client_secret: "sec123".to_string(),
            auth_url: "https://auth.com".to_string(),
            token_url: "https://token.com".to_string(),
            userinfo_url: None,
            redirect_uri: "https://app.com/callback".to_string(),
        };

        let mock_resp =
            r#"{"access_token":"t123","token_type":"Bearer","expires_in":3600,"id_token":"id123"}"#;
        let mock_client = MockHttpClient {
            response_body: mock_resp.to_string(),
            last_request: Mutex::new(None),
        };

        let token_resp =
            Oauth2Client::exchange_code(&config, "mycode", &mock_client, None).unwrap();
        assert_eq!(token_resp.access_token, "t123");
        assert_eq!(token_resp.id_token, Some("id123".to_string()));

        let req = mock_client.last_request.lock().unwrap().clone().unwrap();
        assert_eq!(req.0, "POST");
        assert_eq!(req.1, "https://token.com");
        assert!(req.2.contains("code=mycode"));
        assert!(req.2.contains("client_secret=sec123"));
    }

    #[test]
    fn test_get_user_info() {
        let config = OAuthConfig {
            client_id: "id123".to_string(),
            client_secret: "sec123".to_string(),
            auth_url: "https://auth.com".to_string(),
            token_url: "https://token.com".to_string(),
            userinfo_url: Some("https://userinfo.com".to_string()),
            redirect_uri: "https://app.com/callback".to_string(),
        };

        let mock_resp =
            r#"{"sub":"user123","name":"John Doe","email":"john@example.com","roles":["user"]}"#;
        let mock_client = MockHttpClient {
            response_body: mock_resp.to_string(),
            last_request: Mutex::new(None),
        };

        let user_info = Oauth2Client::get_user_info(&config, "t123", &mock_client).unwrap();
        assert_eq!(user_info.sub, "user123");
        assert_eq!(user_info.name, Some("John Doe".to_string()));
        assert_eq!(user_info.email, Some("john@example.com".to_string()));
        assert_eq!(user_info.roles, Some(vec!["user".to_string()]));

        let req = mock_client.last_request.lock().unwrap().clone().unwrap();
        assert_eq!(req.0, "GET");
        assert_eq!(req.1, "https://userinfo.com");
    }

    #[test]
    fn test_get_user_info_missing_url() {
        let config = OAuthConfig {
            client_id: "id123".to_string(),
            client_secret: "sec123".to_string(),
            auth_url: "https://auth.com".to_string(),
            token_url: "https://token.com".to_string(),
            userinfo_url: None,
            redirect_uri: "https://app.com/callback".to_string(),
        };

        let mock_client = MockHttpClient {
            response_body: String::new(),
            last_request: Mutex::new(None),
        };

        let err = Oauth2Client::get_user_info(&config, "t123", &mock_client).unwrap_err();
        assert!(matches!(err, AuthError::Crypto(_)));
    }

    #[test]
    fn test_parse_oidc_discovery() {
        let metadata_json = r#"{"authorization_endpoint":"https://auth.com","token_endpoint":"https://token.com","userinfo_endpoint":"https://userinfo.com"}"#;
        let config = Oauth2Client::parse_oidc_discovery(
            "id123",
            "sec123",
            "https://app.com/callback",
            metadata_json,
        )
        .unwrap();
        assert_eq!(config.client_id, "id123");
        assert_eq!(config.client_secret, "sec123");
        assert_eq!(config.auth_url, "https://auth.com");
        assert_eq!(config.token_url, "https://token.com");
        assert_eq!(
            config.userinfo_url,
            Some("https://userinfo.com".to_string())
        );
        assert_eq!(config.redirect_uri, "https://app.com/callback");
    }

    #[test]
    fn test_fetch_oidc_config() {
        let metadata_json = r#"{"authorization_endpoint":"https://auth.com","token_endpoint":"https://token.com","userinfo_endpoint":"https://userinfo.com"}"#;
        let mock_client = MockHttpClient {
            response_body: metadata_json.to_string(),
            last_request: Mutex::new(None),
        };

        let config = Oauth2Client::fetch_oidc_config(
            "id123",
            "sec123",
            "https://app.com/callback",
            "https://discovery.com",
            &mock_client,
        )
        .unwrap();

        assert_eq!(config.client_id, "id123");
        assert_eq!(config.auth_url, "https://auth.com");

        let req = mock_client.last_request.lock().unwrap().clone().unwrap();
        assert_eq!(req.0, "GET");
        assert_eq!(req.1, "https://discovery.com");
    }
}
